version: '2'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  website:
    depends_on:
      - 'mongodb'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/web/site'
